version: "3.4"

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: dandi-search-frontend
    container_name: dandi-search-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - rest

  rest:
    build:
      context: rest
      dockerfile: Dockerfile
    image: dandi-search-rest
    container_name: dandi-search-rest
    ports:
      - "8050:8050"
    environment:
      QDRANT_HOST: ${QDRANT_HOST}
      QDRANT_PORT: ${QDRANT_PORT}
      QDRANT_COLLECTION_NAME: ${QDRANT_COLLECTION_NAME}
      QDRANT_VECTOR_SIZE: ${QDRANT_VECTOR_SIZE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DANDI_API_KEY: ${DANDI_API_KEY}
    volumes:
      - ./rest:/app