name: Build and publish REST API production image

on:
  push:
    branches:
      - main
    paths:
      - rest/**

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true # Push is a shorthand for --output=type=registry
        tags: ghcr.io/catalystneuro/dandiset-search-service:latest
        context: rest
        file: rest/Dockerfile
